# Generated by Django 2.1.1 on 2018-10-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='millionaire',
            old_name='image',
            new_name='score',
        ),
        migrations.AddField(
            model_name='millionaire',
            name='cash',
            field=models.FloatField(default=0),
        ),
    ]
