# Generated by Django 2.1.1 on 2018-10-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0003_auto_20181031_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='millionaire',
            name='cash',
            field=models.FloatField(blank=True, default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='millionaire',
            name='cats',
            field=models.IntegerField(blank=True, default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='millionaire',
            name='currency',
            field=models.IntegerField(blank=True, default=1, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='millionaire',
            name='score',
            field=models.BigIntegerField(blank=True, default=0, verbose_name=''),
        ),
    ]
