# Generated by Django 2.1.1 on 2018-11-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0006_millionaire_bastshoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='millionaire',
            name='levelbuild',
            field=models.IntegerField(blank=True, default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='millionaire',
            name='price_bastshoes',
            field=models.IntegerField(blank=True, default=50, verbose_name=''),
        ),
        migrations.AddField(
            model_name='millionaire',
            name='price_cash',
            field=models.IntegerField(blank=True, default=300, verbose_name=''),
        ),
        migrations.AddField(
            model_name='millionaire',
            name='price_cats',
            field=models.IntegerField(blank=True, default=100, verbose_name=''),
        ),
        migrations.AddField(
            model_name='millionaire',
            name='price_levelbuild',
            field=models.IntegerField(blank=True, default=100, verbose_name=''),
        ),
    ]
