# Generated by Django 2.1.1 on 2018-11-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0007_auto_20181106_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='millionaire',
            old_name='price_cash',
            new_name='price_upgraide_currency',
        ),
    ]
