# Generated by Django 2.1.4 on 2019-02-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0010_auto_20190201_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='millionaire',
            name='archer',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='millionaire',
            name='engeneer',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='millionaire',
            name='footer',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='millionaire',
            name='merchant',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='millionaire',
            name='monk',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='millionaire',
            name='peasant',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='millionaire',
            name='rich',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='millionaire',
            name='scientist',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='millionaire',
            name='thief',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='millionaire',
            name='builds',
            field=models.CharField(default='0000000000000000000000000000000000000000000', max_length=43, verbose_name=''),
        ),
    ]
