# Generated by Django 2.1.1 on 2018-10-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersimages',
            name='avatar',
            field=models.BooleanField(default=False),
        ),
    ]
