# Generated by Django 2.1.1 on 2018-10-20 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0002_usersimages_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersimages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 16, 46, 31, 407921, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
