# Generated by Django 2.1.1 on 2018-10-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0003_auto_20181020_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name=''),
        ),
    ]
