# Generated by Django 2.1.1 on 2018-10-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0004_auto_20181020_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalusers',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
