# Generated by Django 2.1.1 on 2018-10-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0005_auto_20181022_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalusers',
            old_name='сity',
            new_name='city',
        ),
    ]
