# Generated by Django 2.1.1 on 2018-10-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0007_auto_20181023_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalusers',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='additionalusers',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalusers',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='additionalusers',
            name='status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
