# Generated by Django 2.1.1 on 2018-10-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0008_auto_20181023_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalusers',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='additionalusers',
            name='phonenumber',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='additionalusers',
            name='status',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
